export const YOUTUBE_HELP_URLS = {
  channel: "https://www.youtube.com/@HTAlchemy",
  appOverviewPrimary: "https://youtu.be/F6VktgCdv70?si=adPz2TfVXnO1LJgq",
  appOverviewSecondary: "https://youtu.be/AqVE3A3KREA?si=BrsEs0pk3f9WrMan",
  seniorSquadOptimization: "https://youtu.be/dGr88GEj6kA?si=wpp-bp0BLyY8_X44",
  seniorEditSkillsAgeWageTsi: "https://youtu.be/2dMgmGJi2OA?si=LlqoDaZTZOK4BfWF",
  youthPlayerList: "https://youtu.be/w7XPrWDktLc?si=wMS-7EUd02BrFxeN",
  youthPlayerDetailsRefresh: "https://youtu.be/0V172HmzmTM?si=1yUzSkKrrfiBWw5f",
  youthSkillsMatrix: "https://youtu.be/ujxpCkRXBws?si=S7SsdGs81qXXuYY5",
  youthRatingsMatrix: "https://youtu.be/gjijN0K04pg?si=tzAZshtZugAb5xeQ",
  youthLineup: "https://youtu.be/3CmcrI0_r7Q?si=VMeZiMHSKTmsUJ9n",
  youthStarPlayer: "https://youtu.be/XZ9bhMXrtGw?si=fW_IPUzyz_VL9Uya",
  youthOptimizeAroundStar: "https://youtu.be/RTyk3aq3GDE?si=zAvcd-X6yVYQJpNl",
  youthRevealValue: "https://youtu.be/Ob81rT3hzvw?si=KpP65SI91UngXC4u",
  youthDoubleReveal: "https://youtu.be/xTe2Z9HdKXA?si=DPs6WyA0P0eUymc-",
  youthOptimizeByRatings: "https://youtu.be/9GatuCbHcGc?si=dsjYE2L9xf9mlFOX",
  youthEstimateValue: "https://youtu.be/Lkoovjqm3c8?si=qD3c6-1PipADgqHP",
} as const;
